"""design

Revision ID: 185f9a4c9051
Revises: b45664fe85cc
Create Date: 2026-05-11 17:53:00.044330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185f9a4c9051'
down_revision: Union[str, Sequence[str], None] = 'b45664fe85cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('HOUSE', 'APARTMENT', 'COMMERCIAL', 'PARTIAL', name='design_type'), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('square', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designs'))
    )
    op.create_table('design_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('room_quantity', sa.Integer(), nullable=False),
    sa.Column('walls_material', sa.Enum('CONCRETE', 'AERATE', 'PLASTERBOARD', name='walls_material'), nullable=False),
    sa.Column('partitions_material', sa.Enum('CONCRETE', 'AERATE', 'PLASTERBOARD', name='walls_material'), nullable=True),
    sa.Column('suspended_ceiling', sa.Boolean(), nullable=False),
    sa.Column('sockets_quantity', sa.Integer(), nullable=True),
    sa.Column('switches_quantity', sa.Integer(), nullable=True),
    sa.Column('communication_sockets_quantity', sa.Integer(), nullable=True),
    sa.Column('light_point_quantity', sa.Integer(), nullable=True),
    sa.Column('built_box', sa.Boolean(), nullable=False),
    sa.Column('power_cable', sa.Boolean(), nullable=False),
    sa.Column('washing_machine', sa.Boolean(), nullable=False),
    sa.Column('dishwasher', sa.Boolean(), nullable=False),
    sa.Column('boiler', sa.Boolean(), nullable=False),
    sa.Column('el_plate', sa.Boolean(), nullable=False),
    sa.Column('water_heater', sa.Boolean(), nullable=False),
    sa.Column('oven', sa.Boolean(), nullable=False),
    sa.Column('other_electric_appliance_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_design_params_design_id_designs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_params'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_params')
    op.drop_table('designs')
    # ### end Alembic commands ###
