"""design_add_unique_param

Revision ID: 566342c8b060
Revises: 185f9a4c9051
Create Date: 2026-05-11 23:40:15.471482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566342c8b060'
down_revision: Union[str, Sequence[str], None] = '185f9a4c9051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_params', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_design_params_design_id'), ['design_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_params', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_design_params_design_id'), type_='unique')

    # ### end Alembic commands ###
