"""estimate_add_status

Revision ID: b2ec184611fb
Revises: 1df46092bd38
Create Date: 2026-05-12 02:44:55.010781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ec184611fb'
down_revision: Union[str, Sequence[str], None] = '1df46092bd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_column('error')

    # ### end Alembic commands ###
